src/Entity/TwitterTrend.php
<?php

namespace Maalls\SocialMediaContentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\UniqueConstraint;
/**
 * @ORM\Entity(repositoryClass="Maalls\SocialMediaContentBundle\Repository\TwitterTrendRepository")
 * @ORM\Table(
 *
 *   uniqueConstraints={
 *        @UniqueConstraint(name="woeid_datetime_name_unique", 
 *            columns={"woeid", "datetime", "name"})
 *    }
 *
 * )
 *
 */
class TwitterTrend
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    // add your own fields

    /**
    * @ORM\Column(type="string", length=32)
    */
    private $woeid;

    /**
    * @ORM\Column(type="string", length=64)
    */
    private $name = '';

    /**
    * @ORM\Column(type="string", length=64, nullable=true)
    */
    private $promoted_content = null;

    /**
    * @ORM\Column(type="string", length=64)
    */
    private $tweet_volume;

    /**
    * @ORM\Column(type="datetime")
    */
    protected $datetime;

    /**
    * @ORM\Column(type="integer")
    */
    private $rank;


    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getWoeid()
    {
        return $this->woeid;
    }

    /**
     * @param mixed $woeid
     *
     * @return self
     */
    public function setWoeid($woeid)
    {
        $this->woeid = $woeid;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPromotedContent()
    {
        return $this->promoted_content;
    }

    /**
     * @param mixed $promoted_content
     *
     * @return self
     */
    public function setPromotedContent($promoted_content)
    {
        $this->promoted_content = $promoted_content;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getTweetVolume()
    {
        return $this->tweet_volume;
    }

    /**
     * @param mixed $tweet_volume
     *
     * @return self
     */
    public function setTweetVolume($tweet_volume)
    {
        $this->tweet_volume = $tweet_volume;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getDatetime()
    {
        return $this->datetime;
    }

    /**
     * @param mixed $datetime
     *
     * @return self
     */
    public function setDatetime($datetime)
    {
        $this->datetime = $datetime;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * @param mixed $rank
     *
     * @return self
     */
    public function setRank($rank)
    {
        $this->rank = $rank;

        return $this;
    }
}

src/Controller/TwitterTrendController.php
<?php

namespace Maalls\SocialMediaContentBundle\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Maalls\SocialMediaContentBundle\Entity\TwitterTrend;


/**
 * @Route("/twitter/trends")
 */
class TwitterTrendController extends Controller
{


    private $woeid;


    public function __construct(\Maalls\SocialMediaContentBundle\Lib\Woeid $woeid)
    {

        $this->woeid = $woeid;

    }

    /**
     * @Route("/", name="twitter_trends")
     * @Template
     */
    public function indexAction(Request $request)
    {

        $locations = $this->woeid->getLocations();

        $rep = $this->getDoctrine()->getManager()->getRepository(TwitterTrend::class);
        $qb = $rep
            ->createQueryBuilder("t")
            ->select("t.name, t.woeid, min(t.rank) as rank")
            ->groupBy("t.name")
            ->addGroupBy("t.woeid")
            ->orderBy("t.name", "ASC");

        $search = $request->query->get("search");

        if($search) {

            $qb->andWhere("t.name LIKE :name")
                ->setParameter("name", "%$search%");

        }
        
        $query = $qb->getQuery();
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $query, 
            $request->query->getInt('page', 1),
            50
        );

        return ["locations" => $locations, "all" => $pagination, "search" => $search];

    }
    /**
     * @Route("/location/{woeid}", name="twitter_trends_location")
     * @Template
     */
    public function locationAction($woeid, Request $request)
    {

        $location = $this->woeid->findLocation($woeid);

        $rep = $this->getDoctrine()->getManager()->getRepository(TwitterTrend::class);

        $lastTrends = $rep->findBy(["woeid" => $woeid], [ "datetime" => "DESC"], 1);

        $lastTrend = null;
        $trends = [];

        if($lastTrends) {

            $lastTrend = $lastTrends[0];
            $trends = $rep->findBy(["woeid" => $woeid, "datetime" => $lastTrend->getDatetime()], ["rank" => "ASC"]);

        }
        
        $qb = $rep
            ->createQueryBuilder("t")
            ->select("t.name, t.woeid, min(t.rank) as rank")
            ->where("t.woeid = :woeid")->setParameter("woeid", $woeid)
            ->groupBy("t.name")
            ->orderBy("t.name", "ASC");

        $search = $request->query->get("search");

        if($search) {

            $qb->andWhere("t.name LIKE :name")
                ->setParameter("name", "%$search%");

        }
        
        $query = $qb->getQuery();
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $query, 
            $request->query->getInt('page', 1),
            50
        );

        return ["search" => $search, "recent" => $trends, "datetime" => $lastTrend ? $lastTrend->getDatetime() : null, "all" => $pagination, "location" => $location];

    }

    /**
     * @Route("/location/{woeid}/{name}", name="twitter_trends_show")
     * @Template
     */
    public function showAction($woeid, $name, Request $request)
    {

        $location = $this->woeid->findLocation($woeid);

        $rep = $this->getDoctrine()->getManager()->getRepository(TwitterTrend::class);

        $trends = $rep

            ->createQueryBuilder("t")
            ->select("t.datetime, t.rank")
            ->where("t.name = :name and t.woeid = :woeid")
            ->setParameters(["name" => $name, "woeid" => $woeid])
            ->getQuery()
            ->getResult();

        return ["name" => $name, "trends" => $trends, "location" => $location];

    }

    protected function getLocations()
    {

        return [
            ["woeid" => "1110809", "name" => "Japan"],
            ["woeid" => "1118370", "name" => "Tokyo"]
        ];

    }

    protected function findLocation($woeid)
    {

        foreach($this->getLocations() as $location) {

            if($location["woeid"] == $woeid) {

                return $location;

            }

        }

        return false;

    }


}

src/Resources/views/twitter_trend/index.html.twig
{% extends '@SocialMediaContent/base.html.twig' %}
{% block meta_title %}
    Trends - Soome
{% endblock %}
{% block breadcrumb %}
    {{ include('@SocialMediaContent/breadcrumb.html.twig', { levels: [{name: 'Trends'}] })}}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-5 col-md-6">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Trending now in Japan <small> last update {{ datetime | ago }}</small></h5>
                    <!--div class="ibox-tools">
                        <a href="" class="btn btn-primary btn-xs">Create new project</a>
                    </div-->
                </div>
                <div class="ibox-content">
                    

                    {{ include('@SocialMediaContent/twitter_trend/rank.html.twig', {'trends': recent }) }}
                </div>
            </div>
        </div>

        <div class="col-lg-5 col-md-6">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>All past Trends in Japan</h5>
                    <!--div class="ibox-tools">
                        <a href="" class="btn btn-primary btn-xs">Create new project</a>
                    </div-->
                </div>
                <div class="ibox-content">
                    
                    <form>
                        <div class="m-b-lg">

                           <div class="input-group"><input type="text" name="search" value="{{ search }}" placeholder="Search" class="form-control-sm form-control"> <span class="input-group-btn">
                                    <input type="submit" class="btn btn-sm btn-primary" value="Go" /> </span></div>

                           
                        </div>
                    </form>
                    {{ include('@SocialMediaContent/twitter_trend/list.html.twig', {'trends': all }) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/Resources/views/twitter_trend/list.html.twig
<div class="project-list">

    <div class="navigation text-center">
        {{ knp_pagination_render(trends) }}
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Top Rank</th>
                <th>link</th>
            </tr>
        </thead>
        <tbody>
            {% if trends | length %}

                {% for trend in trends %}
                    <tr>
                        <td><a href="{{ path('twitter_trends_show', {name: trend.name, woeid: trend.woeid }) }}">{{ trend.name }}</a></td>
                        <td>{{ trend.rank }}</td>
                        <td><a target="_blank" href="https://twitter.com/search?q={{ trend.name | url_encode }}"><i class="fa fa-external-link"></i></a></td>
                    </tr>
                {% endfor %}

            {% else %}
                <tr><td colspan="3">No results.</td></tr>
            {% endif %}
        </tbody>
    </table>

    <div class="navigation text-center">
        {{ knp_pagination_render(trends) }}
    </div>
</div>

src/Resources/views/twitter_trend/location.html.twig
{% extends '@SocialMediaContent/base.html.twig' %}
{% block meta_title %}
    Trends - Soome
{% endblock %}
{% block breadcrumb %}
    {{ include('@SocialMediaContent/breadcrumb.html.twig', { levels: [{name: 'Trends', link: path('twitter_trends')  }, {name: location.name }] })}}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-5 col-md-6">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Trending now <small> {% if datetime %}last update {{ datetime | ago }}</small>{% endif %}</h5>
                    <!--div class="ibox-tools">
                        <a href="" class="btn btn-primary btn-xs">Create new project</a>
                    </div-->
                </div>
                <div class="ibox-content">
                    

                    {{ include('@SocialMediaContent/twitter_trend/rank.html.twig', {'trends': recent }) }}
                </div>
            </div>
        </div>

        <div class="col-lg-5 col-md-6">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>All past Trends</h5>
                    <!--div class="ibox-tools">
                        <a href="" class="btn btn-primary btn-xs">Create new project</a>
                    </div-->
                </div>
                <div class="ibox-content">
                    
                    <form>
                        <div class="m-b-lg">

                           <div class="input-group"><input type="text" name="search" value="{{ search }}" placeholder="Search" class="form-control-sm form-control"> <span class="input-group-btn">
                                    <input type="submit" class="btn btn-sm btn-primary" value="Go" /> </span></div>

                           
                        </div>
                    </form>
                    {{ include('@SocialMediaContent/twitter_trend/list.html.twig', {'trends': all }) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/Resources/views/twitter_trend/rank.html.twig
<div class="project-list">

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Rank</th>
                <th>Name</th>
                <th>Volume</th>
                <th>link</th>
            </tr>
        </thead>
        <tbody>
            {% for trend in trends %}
                <tr>
                    <td>{{ trend.rank }}</td>
                    <td><a href="{{ path('twitter_trends_show', {name: trend.name, woeid: trend.woeid }) }}">{{ trend.name }}</a></td>
                    <td>{{ trend.tweetVolume ? trend.tweetVolume | number_format : '-' }}</td>
                    <td><a target="_blank" href="https://twitter.com/search?q={{ trend.name | url_encode }}"><i class="fa fa-external-link"></i></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

src/Resources/views/twitter_trend/show.html.twig
{% extends '@SocialMediaContent/base.html.twig' %}
{% block meta_title %}
    {{ name }} Trend - Soome
{% endblock %}

{% block breadcrumb %}
    {{ include('@SocialMediaContent/breadcrumb.html.twig', { levels: [{link: path('twitter_trends'), name: 'Trends'}, {name: location.name, link: path('twitter_trends_location', {woeid: location.woeid }) }, {name: name }] })}}
{% endblock %}
{% block content %}

            <div class="row">
                
                <div class="col-md-6">
                    

                    <div class="ibox">
                        <div class="ibox-content">

                            
                            <div class="row">
                            
                                    <div class="col-lg-12">

                                        <h4>{{ name }} trend in {{ location.name }}</h4>
                                        
                                        <div id="trend_chart" style="width: 100%; height: 500px"></div>

                                    </div>

                            </div>


                        </div>
                    </div>



                </div>

            </div>

{% endblock %}


{% block app_javascripts %}

 
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

        <script type="text/javascript">
          google.charts.load('current', {'packages':['corechart']});
          google.charts.setOnLoadCallback(drawChart);

          
          function drawChart() {
            var array = [
            ['date', 'Rank'],

            {% for trend in trends %}
                [new Date('{{ trend.datetime.format("Y-m-dTH:i:00") }}'), {{ trend.rank }}] {% if not loop.last %},{% endif %} {{ '\n' }}
            {% endfor %}

          ];
            var data = google.visualization.arrayToDataTable(array);

            var options = {
                title: '',
                legend: { position: 'none' },
                vAxis: { 
                    title: 'Rank',
                    direction: -1,
                    

                    viewWindow:{
                        
                        min:1
                        

                    },
                    step: 1,

                    max: 50,
                    format: '0'
                },
                chartArea: {'width': '80%', 'height': '80%'}

            };

            var chart = new google.visualization.LineChart(document.getElementById('trend_chart'));

            function selectHandler() {

                console.log("handler", chart.getSelection());

                var selection = chart.getSelection();

                if(selection.length) {

                    var item = selection[0];
                    if (item.row != null && item.column != null) {

                        console.log("selection", item.row, item.column);

                    } 

                }

            }

            google.visualization.events.addListener(chart, 'select', selectHandler);

            chart.draw(data, options);

            $(window).resize(function() {

                if(this.resizeTO) clearTimeout(this.resizeTO);
                this.resizeTO = setTimeout(function() {
                    $(this).trigger('resizeEnd');
                }, 500);
            });

            //redraw graph when window resize is completed  
            $(window).on('resizeEnd', function() {
                chart.draw(data, options);
            });

          }


        </script>



{% endblock %}