src/Entity/TwitterUser.php
<?php

namespace Maalls\SocialMediaContentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Maalls\SocialMediaContentBundle\Repository\TwitterUserRepository")
 * @ORM\Table(indexes={
 *   @ORM\Index(name="screen_name", columns={"screen_name"}),
 *   @ORM\Index(name="lang", columns={"lang", "followers_count"}),
 *   @ORM\Index(name="status", columns={"status", "profile_updated_at"}),
 *   @ORM\Index(name="score", columns={"lang", "score"})
 * })
 *
 */
class TwitterUser
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="bigint", options={"unsigned"=true})
     */
    private $id;

    // add your own fields


    /**
    * @ORM\Column(type="string", length=64, nullable=true)
    */
    private $name = '';

    /**
    * @ORM\Column(type="string", length=64, nullable=true)
    */
    private $screen_name = '';

    /**
    * @ORM\Column(type="text", nullable=true)
    */
    private $description = '';

    /**
    * @ORM\Column(type="string", length=8, nullable=true)
    */
    private $lang = '';

    /**
    * @ORM\Column(type="string", length=256, nullable=true)
    */
    protected $location = '';


    /**
    * @ORM\Column(type="string", length=1024, nullable=true)
    */
    protected $url = '';

    /**
    * @ORM\Column(type="boolean", nullable=true)
    */
    private $verified;

    /**
    * @ORM\Column(type="boolean", nullable=true)
    */
    private $protected;

    /**
     * @ORM\Column(type="bigint", options={"unsigned"=true}, nullable=true)
     */
    private $followers_count = 0;

    /**
     * @ORM\Column(type="bigint", options={"unsigned"=true}, nullable=true)
     */
    private $friends_count = 0;

    /**
     * @ORM\Column(type="integer", options={"unsigned"=true}, nullable=true)
     */
    private $listed_count = 0;


    /**
     * @ORM\Column(type="integer", options={"unsigned"=true}, nullable=true)
     */
    private $post_period_median;

    /**
     * @ORM\Column(type="integer", options={"unsigned"=true}, nullable=true)
     */
    private $retweet_median;

    /**
     * @ORM\Column(type="integer", options={"unsigned"=true}, nullable=true)
     */
    private $favorite_median;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $retweet_rate;

    /**
     * @ORM\Column(type="integer", options={"unsigned"=true}, nullable=true)
     */
    private $score;

     /**
    * @ORM\Column(type="datetime")
    */
    private $updated_at;

    /**
    * @ORM\Column(type="datetime", nullable=true)
    */
    private $profile_updated_at;

    /**
    * @ORM\Column(type="datetime", nullable=true)
    */
    private $timeline_updated_at;

    /**
     * @ORM\OneToMany(targetEntity="Maalls\SocialMediaContentBundle\Entity\Tweet", mappedBy="user")
     */
    private $tweets;

    /**
    * @ORM\Column(type="datetime", nullable=true)
    */
    private $friends_updated_at;

    /**
     * @ORM\OneToMany(targetEntity="Maalls\SocialMediaContentBundle\Entity\TwitterUserFollower", mappedBy="follower")
     */
    private $friends;

    /**
    * @ORM\Column(type="datetime", nullable=true)
    */
    private $followers_updated_at;

    /**
     * @ORM\OneToMany(targetEntity="Maalls\SocialMediaContentBundle\Entity\TwitterUserFollower", mappedBy="twitterUser")
     */
    private $followers;

    /**
     * @ORM\OneToMany(targetEntity="Maalls\SocialMediaContentBundle\Entity\UserTag", mappedBy="user")
     */
    private $userTags = [];

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $status = 200;

    public function __construct() {
    
        $this->tweets = new \Doctrine\Common\Collections\ArrayCollection();
        $this->followers = new \Doctrine\Common\Collections\ArrayCollection();
        $this->friends = new \Doctrine\Common\Collections\ArrayCollection();
        $this->userTags = new \Doctrine\Common\Collections\ArrayCollection();
    }


    public function hasTag($tag)
    {

        foreach($this->getUserTags() as $userTag) {

            if($userTag->getTag()->getId() == $tag->getId()) {

                return $userTag;

            }

        }

        return false;

    }


    public function getUserTags()
    {

        return $this->userTags;

    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getScreenName()
    {
        return $this->screen_name;
    }

    /**
     * @param mixed $screen_name
     *
     * @return self
     */
    public function setScreenName($screen_name)
    {
        $this->screen_name = $screen_name;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * @param mixed $lang
     *
     * @return self
     */
    public function setLang($lang)
    {
        $this->lang = $lang;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * @param mixed $location
     *
     * @return self
     */
    public function setLocation($location)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * @param mixed $url
     *
     * @return self
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getVerified()
    {
        return $this->verified;
    }

    /**
     * @param mixed $verified
     *
     * @return self
     */
    public function setVerified($verified)
    {
        $this->verified = $verified;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getProtected()
    {
        return $this->protected;
    }

    /**
     * @param mixed $protected
     *
     * @return self
     */
    public function setProtected($protected)
    {
        $this->protected = $protected;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFollowersCount()
    {
        return $this->followers_count;
    }

    /**
     * @param mixed $followers_count
     *
     * @return self
     */
    public function setFollowersCount($followers_count)
    {
        $this->followers_count = $followers_count;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFriendsCount()
    {
        return $this->friends_count;
    }

    /**
     * @param mixed $friends_count
     *
     * @return self
     */
    public function setFriendsCount($friends_count)
    {
        $this->friends_count = $friends_count;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getListedCount()
    {
        return $this->listed_count;
    }

    /**
     * @param mixed $listed_count
     *
     * @return self
     */
    public function setListedCount($listed_count)
    {
        $this->listed_count = $listed_count;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPostPeriodMedian()
    {
        return $this->post_period_median;
    }

    /**
     * @param mixed $post_period_median
     *
     * @return self
     */
    public function setPostPeriodMedian($post_period_median)
    {
        $this->post_period_median = $post_period_median;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getRetweetMedian()
    {
        return $this->retweet_median;
    }

    /**
     * @param mixed $retweet_median
     *
     * @return self
     */
    public function setRetweetMedian($retweet_median)
    {
        $this->retweet_median = $retweet_median;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFavoriteMedian()
    {
        return $this->favorite_median;
    }

    /**
     * @param mixed $favorite_median
     *
     * @return self
     */
    public function setFavoriteMedian($favorite_median)
    {
        $this->favorite_median = $favorite_median;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getRetweetRate()
    {
        return $this->retweet_rate;
    }

    /**
     * @param mixed $retweet_rate
     *
     * @return self
     */
    public function setRetweetRate($retweet_rate)
    {
        $this->retweet_rate = $retweet_rate;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * @param mixed $score
     *
     * @return self
     */
    public function setScore($score)
    {
        $this->score = $score;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param mixed $updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return mixed
     */

src/Resources/views/twitter_user/breadcrumb.html.twig
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2></h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ path('smc_home') }}">Home</a>
            </li>
            <li>
                <a>Twitter</a>
            </li>
            <li>
                <a href="{{ path('twitter_users') }}">Users</a>
            </li>
            <li class="active">
                {{ user.name }} <small>@{{ user.screenName }}</small>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

src/Resources/views/twitter_user/followers.html.twig
{% extends '@SocialMediaContent/base.html.twig' %}

{% block breadcrumb %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2></h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ path('smc_home') }}">Home</a>
                </li>
                <li>
                    <a>Twitter</a>
                </li>
                <li>
                    <a href="{{ path('twitter_users') }}">Users</a>
                </li>
                <li>
                    <a href="{{ path('twitter_users_show', {id: user.id }) }}">{{ user.name }} @{{ user.screenName }}</a>
                </li>
                <li>
                    Followers
                </li>
                
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
{% endblock %}

{% block content %}

    {{ include('@SocialMediaContent/twitter_user/list.html.twig', {'pagination': pagination, 'getter': 'follower' }) }}

{% endblock %}

src/Resources/views/twitter_user/following.html.twig
{% extends '@SocialMediaContent/base.html.twig' %}

{% block breadcrumb %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2></h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ path('smc_home') }}">Home</a>
                </li>
                <li>
                    <a>Twitter</a>
                </li>
                <li>
                    <a href="{{ path('twitter_users') }}">Users</a>
                </li>
                <li>
                    <a href="{{ path('twitter_users_show', {id: user.id }) }}">{{ user.name }} @{{ user.screenName }}</a>
                </li>
                <li>
                    Following
                </li>
                
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
{% endblock %}

{% block content %}

    {{ include('@SocialMediaContent/twitter_user/list.html.twig', {'pagination': pagination }) }}

{% endblock %}

src/Resources/views/twitter_user/index.html.twig
{% extends '@SocialMediaContent/base.html.twig' %}

{% block breadcrumb %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2></h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ path('smc_home') }}">Home</a>
                </li>
                <li>
                    <a>Twitter</a>
                </li>
                <li>
                    <a href="{{ path('twitter_users') }}">Users</a>
                </li>
                
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
{% endblock %}

{% block content %}

    {{ include('@SocialMediaContent/twitter_user/list.html.twig', {'pagination': pagination }) }}

{% endblock %}

src/Resources/views/twitter_user/list.html.twig
<div class="ibox">
    <div class="ibox-title">
        <h5>{{ pagination.getTotalItemCount ? (pagination.getTotalItemCount | number_format) : '' }} Twitter accounts</h5>
        <!--div class="ibox-tools">
            <a href="" class="btn btn-primary btn-xs">Create new project</a>
        </div-->
    </div>
    <div class="ibox-content">
        

        <div class="project-list">

            <div class="navigation">
                {{ knp_pagination_render(pagination) }}
            </div>

            <table class="table table-hover">
                <tbody>


                    {% for user in pagination %}

                        {% if getter is defined %}
                            {% set user = attribute(user, getter) %}
                        {% endif %}
                        {% if (loop.index - 1) is divisible by(20) %}
                            
                            <tr>

                                <th>Position</th>
                                <th></th>
                                <th>Name</th>
                                <th>description</th>
                                {% for h in [
                                    {label: 'Followers', field: 'followers_count'}, 
                                    {label: 'Following', field: 'friends_count'}, 
                                    {label: 'Listed', field: 'listed_count'},
                                    {label: 'RT/post', field: 'score'},
                                    {label: 'Fav/post', field: 'favorite_median'},

                                    ] 
                                %}
                                    <th class="text-right"> 

                                        {{ knp_pagination_sortable(pagination, h.label, 'u.' ~ h.field) }}
                                        {% if pagination.isSorted('u.' ~ h.field) %} 

                                            {% if pagination.direction == 'asc' %}
                                                <i class="fa fa-sort-up" />
                                            {% else %}
                                                <i class="fa fa-sort-down" />
                                            {% endif %}


                                        {% endif %}

                                    </th>
                                {% endfor %}
                            </tr>
                        
                        {% endif %}

                        <tr>
                            <td>
                                <a href="{{ path('twitter_users_show', {id: user.id}) }}">{{ (loop.index + ((pagination.page ?  pagination.page - 1 : 0) * 100)) | number_format }}</a>
                            </td>
                            <td>
                                {% if user.screenName %}
                                    <img src="https://avatars.io/twitter/{{ user.screenName }}" width="35" height="35">
                                {% endif %}
                            </td>
                            <td>
                                {% if user.name %}
                                    <a href="{{ path('twitter_users_show', {id: user.id}) }}">{{ user.name }}</a>
                                    {% if user.verified %}<i style="color:#1dcaff" class="fa fa-check-circle"></i>{% endif %}
                                    {% if user.protected %}<i  class="fa fa-lock"></i>{% endif %} <a href="https://twitter.com/{{user.screenName }}" target="_blank"><i class="fa fa-external-link"></i></a>
                                    <br/>@{{ user.screenName }}
                                {% else %}
                                    User {{ user.id }} <a href="https://twitter.com/{{user.screenName }}" target="_blank"><i class="fa fa-external-link"></i></a>
                                    <br/><small>Information not collected yet, please wait.</small>
                                {% endif %}

                                
                                
                                
                            </td>

                            <td>
                                {{ user.description }}
                            </td>
                           
                            <td class="text-right">
                                {{ user.protected and not user.followersCount ? 'NA' : (user.followersCount | number_format) }}
                                {{ user.followersUpdatedAt ? '*' : '' }}
                            </td>
                            <td class="text-right">
                                {{ user.friendsCount | number_format }}
                            </td>
                            <td class="text-right">
                                {{ not user.timelineUpdatedAt or user.protected and not user.listedCount ? 'NA' : (user.listedCount | number_format) }}
                            </td>
                            <td class="text-right">
                                {{ not user.timelineUpdatedAt or user.protected and not user.retweetMedian ? 'NA' : (user.retweetMedian | number_format) }}
                            </td>
                            
                            <td class="text-right">
                                {{ not user.timelineUpdatedAt or user.protected and not user.favoriteMedian ? 'NA' : (user.favoriteMedian | number_format) }}
                            </td>
                            
                        </tr>
                    {% endfor %}

                </tbody>
            </table>

            <div class="navigation">
                {{ knp_pagination_render(pagination) }}
            </div>
        </div>

    </div>
</div>

src/Resources/views/twitter_user/profile.html.twig
<div class="row">

    <div class="col-lg-12">

        <div class="profile-image">
            <img src="https://avatars.io/twitter/{{ user.screenName }}" class="img-circle circle-border m-b-md" alt="profile">
        </div>
        <div class="profile-info">
            <div class="">
                <div>
                    <h2 class="no-margins">
                        {{ user.name }} 
                        {% if user.verified %}<i style="color:#1dcaff" class="fa fa-check-circle"></i>{% endif %}
                        {% if user.protected %}<i  class="fa fa-lock"></i>{% endif %}

                        <a class="pull-right" target="_blank" href="https://twitter.com/{{ user.screenName }}"><i class="fa fa-external-link"></i></a>

                    </h2>
                    <h4>@{{ user.screenName }}</h4>
                    <p>
                        {{ user.description }}
                    </p>

                    <p>
                        <strong>Location:</strong> {{ user.location }}<br/>
                        <strong>Lang:</strong> {{ user.lang }}<br/>
                        {% if user.url %}
                            <strong>Website:</strong> <a href="{{ user.url }}" target="_blank">{{ user.url }}</a><br/>
                        {% endif %}
                    </p>

                </div>
            </div>
        </div>

    </div>

</div>



<div class="row m-t-lg">
    
    {% for stat in stats.stats %}

        <div class="col-md-4">
        
            <h5>
            
            {% if stat.link %}
                <a href="{{ stat.link }}">
            {% endif %}
               <strong> {{ stat.value | number_format }}</strong> {{ stat.name }}
            {% if stat.link %}
                </a>
            {% endif %}

            </h5>
        </div>

    {% endfor %}
</div>

<div class="row">

    <div class="col-sm-12">
        <p>
            <small class="pull-right">

                profile updated {{ user.profileUpdatedAt | ago }}
                {% if user.followersUpdatedAt %}
                    <br/>followers updated {{ user.followersUpdatedAt | ago }}
                {% endif %}

            </small>
            
        </p>
    </div>

</div>

<div class="row">

    <div class="col-sm-12">
        {{ render(controller(
            'Maalls\\SocialMediaContentBundle\\Controller\\UserTagController::select',
            { 'user': user.id }
        )) }}
    </div>

</div>

src/Resources/views/twitter_user/retweeters.html.twig
<h4>{{ list | length | number_format }} Retweets from</h4>



{% if not list | length  %}

    <p>No retweet found in the database.</p>

{% else %}
<table class="table">
    <tr>

        <th>Name</th>
        <th class="text-right">Followers</th>
    {% set total_followers = 0 %}
    {% for item in list %}
        {% set user = item.user is defined ? item.user : item %}

        <tr>
            <td>
                <a href="{{ path('twitter_users_show', {id: user.id }) }}">
                    <img height="20" src="https://avatars.io/twitter/{{ user.screenName }}?size=mini"  /> 
                    {{ user.name }}
                    @{{ user.screenName }} 
                </a>

                <a target="_blank" href="https://twitter.com/{{ user.screenName }}">
                    <i class="fa fa-external-link"></i>
                </a>
            </td>
            <td class="text-right">
                {{ user.followersCount | number_format }}
            </td>

        </tr>
        {% set total_followers = total_followers + user.followersCount %}
    {% endfor %}

    <tr>
        <th>Total</th>
        <th class="text-right">{{ total_followers | number_format }}</th>
    </tr>
</table>
{% endif %}

src/Resources/views/twitter_user/show.html.twig
{% extends '@SocialMediaContent/base.html.twig' %}
{% block meta_title %}
    {{ user.name }} - Soome
{% endblock %}
{% block stylesheets %}

    <link rel="stylesheet" href="{{ asset('bundles/inspinia/chartist/chartist.min.css') }}?v=1.4">

    <style>

        .ct-series-a .ct-line {
              /* Set the colour of this series line */
              stroke: red;
              /* Control the thikness of your lines */
              stroke-width: 2px;
              stroke-linecap: square;
              
            }
    </style>
{% endblock %}
{% block breadcrumb %}
    {{ include('@SocialMediaContent/twitter_user/breadcrumb.html.twig', {user: user}) }}
{% endblock %}
{% block content %}

            <div class="row">
                
                <div class="col-md-6">
                    

                    <div class="ibox">
                        <div class="ibox-content">

                            {{ include('@SocialMediaContent/twitter_user/profile.html.twig', {user: user, stats: stats}) }}

                            <div class="row">
                                <hr />
                                {% if user.timelineUpdatedAt %}
                                    <div class="col-lg-12">

                                        <h4>Retweet trend</h4>
                                        
                                        <div id="retweet_chart" style="width: 100%; height: 500px"></div>

                                    </div>

                                    <div class="col-lg-12">

                                        
                                        
                                        
                                    </div>
                                {% else  %}

                                    <div class="col-lg-12">   
                                         <p>Untracked user. <a href="{{ path('twitter_users_timeline_update', {id: user.id}) }}">track once</a></p>
                                    </div>
                                {% endif %}

                            </div>


                        </div>
                    </div>



                </div>

                <div class="col-lg-6">

                    {{ include("@SocialMediaContent/twitter_user/timeline/timeline.html.twig", {user: user, timeline: timeline})}}

                </div>
            </div>

{% endblock %}


{% block app_javascripts %}

    {% if user.timelineUpdatedAt %}
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

        <script type="text/javascript">
          google.charts.load('current', {'packages':['corechart']});
          google.charts.setOnLoadCallback(drawChart);

          
          function drawChart() {
            var array = [
            ['day', 'RT'],

            {% for stats in stats.trends.retweets %}
                [{{ loop.index }}, {{ stats }}] {% if not loop.last %},{% endif %}
            {% endfor %}

          ];
            var data = google.visualization.arrayToDataTable(array);

            var options = {
                title: '',
                curveType: 'function',
                legend: { position: 'none' },
                vAxis: { 
                    viewWindow:{
                        
                        min:0
                    }
                },
                chartArea: {'width': '80%', 'height': '80%'}

            };

            var chart = new google.visualization.LineChart(document.getElementById('retweet_chart'));

            function selectHandler() {

                console.log("handler", chart.getSelection());

                var selection = chart.getSelection();

                if(selection.length) {

                    var item = selection[0];
                    if (item.row != null && item.column != null) {

                        console.log("selection", item.row, item.column);

                    } 

                }

            }

            google.visualization.events.addListener(chart, 'select', selectHandler);

            chart.draw(data, options);

            $(window).resize(function() {

                if(this.resizeTO) clearTimeout(this.resizeTO);
                this.resizeTO = setTimeout(function() {
                    $(this).trigger('resizeEnd');
                }, 500);
            });

            //redraw graph when window resize is completed  
            $(window).on('resizeEnd', function() {
                chart.draw(data, options);
            });

          }


        </script>
    {% endif %}


{% endblock %}